### ISSUE TITLE
@cartamd/plugin-component/svelte

### ISSUE THREAD

**Issue by rzeradev** [BearToCode/carta#108]
First of all thank you all for your efforts on Carta. I was using mdsvex but it didnt work my needs. Carta works perfectly all plugins tested and working but one. the plugin-component doesn't seem to work (likely I'm missing something):

Simple test with the h1 tag returns the h1 in the compiled markdown but seems to strip the text from the node

`<h1>Some Text</h1>`

turns into

`<h1 class="text-2xl font-bold"></h1>`

 I tried <Slot /> as said in the docs but it justs adds a template tag inside the h1
 
`<h2 id="" class="font-bold text-2xl"><template data-slot=""></template></h2>`

I'm fetching data from db on +page.server.ts and using render there so in the +page.svelte I can use **PreRendered**

**Comment by BearToCode** [comment]
Hello! It's always nice hearing about people appreciating my work :)

When using pre-rendering you need to [manually initialize components](https://beartocode.github.io/carta/plugins/component#usage-with-pre-rendering) so that they become reactive, otherwise they are not mounted.

There is actually a bug with `<Slot />` and SSR. I just fixed it, just need to update the plugin!

### Extra tip

I suggest you store/cache the rendered HTML if you are able to do so. Rendering can be quite time expensive for the server, and even 300ms can make your site feel slower.

**Comment by rzeradev** [comment]
Awsome looking for `template` instead of `div` fixed the issue and now everything works perfectly! Since my project it's a blog I'll defenitely add caching to the routes, thanks for the tip and for the quick reply. I'm just getting started playing with carta, once I get the hang of it I'll try to contribute to the project. Loving it so for! Thanks.
