### ISSUE TITLE
Both recommended sanitizers don't work on the server side.

### ISSUE THREAD

**Issue by evwltrs** [BearToCode/carta#44]
Both isomorphic-dompurify and sanitize-html don't work on Cloudflare workers.

In the case of isomorphic-dompurify this is because it tries to access window on the server. This issue is documented here https://github.com/kkomelin/isomorphic-dompurify/issues/228

sanitize-html uses path which is unsupported on cloudflare workers.

isomorphic-dompurify would work perfectly if we could somehow stop it from trying to use window on the server side.

What do you recommend we do in this case?

**Comment by BearToCode** [comment]
Hello, I checked out the link you sent and it looks the issue is related to isomorphic-DOMPurify erroneously thinking it is working client-side.

What runtime do Cloudflare workers use? Because, from what you said, it looks like they are neither on a browser-like environment with access to Web API, nor on nodejs(as path is not available).

Anyway, if the problem is just isomorphic-DOMPurify thinking it is running on the client, you could install DOMPurify and jsDOM and create your own isomorphic version, which done by just updating the following:

```ts
import { browser } from '$app/environment'; // <== new
 
function importModule(requiredModule) {
    return requiredModule && requiredModule.default || requiredModule;
}

function initDOMPurifyWithJSDOM() {
  const DOMPurifyInitializer = importModule(require('dompurify'));
  const { JSDOM } = importModule(require('jsdom'));
  const { window } = new JSDOM('<!DOCTYPE html>');
  return DOMPurifyInitializer(window);
}

function resolveDOMPurify() {
  // const isClientSide = typeof window !== 'undefined'; <== remove this
  const isClientSide = browser; // <== use this instead
  return isClientSide ? importModule(require('dompurify')) : initDOMPurifyWithJSDOM();
}

module.exports = global.DOMPurify = global.DOMPurify || resolveDOMPurify();
```

I'm not 100% this will work, so let me know.

Anyway, for sanitize-html maybe you could manually install [path](https://www.npmjs.com/package/path).

**Comment by evwltrs** [comment]
https://github.com/jill64/universal-sanitizer 

I found this alternative sanitzer and it works perfectly on both SSR and the browser. :fire:
